name: muse-lsl-env
channels:
- defaults
dependencies:
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2017.7.27.1=py36hd973bb6_0
- cycler=0.10.0=py36hfc81398_0
- freetype=2.8=h143eb01_0
- intel-openmp=2018.0.0=h68bdfb3_7
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=hd939716_3
- libgfortran=3.0.1=h93005f0_2
- libpng=1.6.32=h6184301_3
- matplotlib=2.1.0=py36h5068139_0
- mkl=2018.0.0=h5ef208c_6
- ncurses=6.0=ha932d30_1
- numpy=1.13.3=py36h2cdce51_0
- openssl=1.0.2m=h86d3e6a_0
- pandas=0.21.0=py36hfed917e_1
- patsy=0.4.1=py36ha1b3fa5_0
- pexpect=4.2.1=py36h3eac828_0
- pip=9.0.1=py36h1555ced_4
- ptyprocess=0.5.2=py36he6521c3_0
- pyparsing=2.2.0=py36hb281f35_0
- python=3.6.3=hc655967_3
- python-dateutil=2.6.1=py36h86d2abb_1
- pytz=2017.2=py36h2e7dfbc_1
- readline=7.0=h81b24a6_3
- scikit-learn=0.19.1=py36hffbff8c_0
- scipy=1.0.0=py36h1de22e9_0
- seaborn=0.8.0=py36h74df97e_0
- setuptools=36.5.0=py36h2134326_0
- six=1.11.0=py36h0e22d5e_1
- sqlite=3.20.1=h900c3b0_1
- statsmodels=0.8.0=py36h9c68fc9_0
- tk=8.6.7=hcdce994_1
- tornado=4.5.2=py36h468dda9_0
- wheel=0.29.0=py36h3597b6d_1
- xz=5.2.3=ha24016e_1
- zlib=1.2.11=h60db283_1
- pip:
  - bitstring==3.1.5
  - enum-compat==0.0.2
  - pygatt==3.2.0
  - pylsl==1.10.5
  - pyserial==3.4
  - vispy 
  - mne
  - PyQt5
prefix: /Users/mikeonly/Anaconda/envs/muse-lsl-env

